### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by kengruven** [Bogdanp/racket-protocol-buffers#1]
The [protobuf docs](https://protobuf.dev/programming-guides/proto2/) (version 2 and version 3) say:

> To add comments to your .proto files, use C/C++-style // and /* ... */ syntax.

But:
- When I run [the example](https://github.com/Bogdanp/racket-protocol-buffers/blob/master/protocol-buffers/protocol-buffers-manual.scrbl#L25) as written, it works.
- When I change the empty `""` (line between "syntax" and "message") to `"// hello"`, it still works.
- When I change it to `"/* hello */"`, it fails with:

> unexpected character: /

**Comment by Bogdanp** [comment]
Thanks for the report! Commit https://github.com/Bogdanp/racket-protocol-buffers/commit/2fd8170dad45283de4d82451c6aa18042b708b54 should fix this.

**Comment by kengruven** [comment]
Thanks!  Looks good to me.  As soon as it's in raco, I'll give it a try.
