### ISSUE TITLE
Default to proto2?

### ISSUE THREAD

**Issue by kengruven** [Bogdanp/racket-protocol-buffers#2]
I previously thought that the "syntax" line was mandatory, but [the proto3 guide says](https://protobuf.dev/programming-guides/proto3/):

> The first line of the file specifies that you’re using proto3 syntax: if you don’t do this the protocol buffer compiler will assume you are using [proto2](https://protobuf.dev/programming-guides/proto2).

Could r-p-b support this default?  FWIW, I think all the other protobuf libraries I've used (including the official one) print a warning if you don't declare a specific "syntax".

**Comment by Bogdanp** [comment]
Thanks, I missed that, too. Should be fixed now.
